#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

DATA_DIR="${CONFIG_DIR}" && export DATA_DIR

cd "${APP_DIR}" || exit 1

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 \
     manage.py run_conreq \
     --disable-preconfig